//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerServiceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЖурналДействий
    {
        public int idДействия { get; set; }
        public Nullable<int> idМатериал { get; set; }
        public Nullable<int> idЗаказ { get; set; }
        public Nullable<decimal> Количество { get; set; }
        public string ТипДвижения { get; set; }
        public string Комментарий { get; set; }
        public Nullable<int> idПользователь { get; set; }
        public Nullable<System.DateTime> ДатаДвижения { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Материал Материал { get; set; }
        public virtual Пользователь Пользователь { get; set; }
    }
}
