//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerServiceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.СоставЗаказа_Материалы = new HashSet<СоставЗаказа_Материалы>();
            this.СоставЗаказа_Услуги = new HashSet<СоставЗаказа_Услуги>();
            this.Счет = new HashSet<Счет>();
        }
    
        public int idЗаказ { get; set; }
        public string ИмяУстройства { get; set; }
        public string СерийныйНомер { get; set; }
        public Nullable<int> idТипУстройства { get; set; }
        public string Неисправность { get; set; }
        public Nullable<int> idКлиент { get; set; }
        public Nullable<int> idПользователь { get; set; }
        public Nullable<System.DateTime> ДатаЗаказа { get; set; }
        public Nullable<int> idСтатус { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Статус Статус { get; set; }
        public virtual ТипУстройства ТипУстройства { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаказа_Материалы> СоставЗаказа_Материалы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаказа_Услуги> СоставЗаказа_Услуги { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Счет> Счет { get; set; }
    }
}
