//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerServiceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материал
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материал()
        {
            this.СоставЗаказа_Материалы = new HashSet<СоставЗаказа_Материалы>();
            this.Склад = new HashSet<Склад>();
        }
    
        public int idМатериал { get; set; }
        public string Наименование { get; set; }
        public string Описание { get; set; }
        public Nullable<decimal> БазоваяСтоимость { get; set; }
        public Nullable<decimal> РозничнаяЦена { get; set; }
        public Nullable<int> idТипМатериала { get; set; }
        public Nullable<int> idЕдиницыИзмерения { get; set; }
        public Nullable<System.DateTime> ДатаДобавления { get; set; }
    
        public virtual ЕдиницыИзмерения ЕдиницыИзмерения { get; set; }
        public virtual ТипМатериала ТипМатериала { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаказа_Материалы> СоставЗаказа_Материалы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Склад> Склад { get; set; }
    }
}
