//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerServiceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Платеж
    {
        public int idПлатеж { get; set; }
        public Nullable<int> idСчет { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<int> idСпособОплаты { get; set; }
        public Nullable<System.DateTime> ДатаПлатежа { get; set; }
    
        public virtual СпособОплаты СпособОплаты { get; set; }
        public virtual Счет Счет { get; set; }
    }
}
