//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerServiceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склад
    {
        public int idСклад { get; set; }
        public Nullable<int> idМатериал { get; set; }
        public Nullable<decimal> Количество { get; set; }
    
        public virtual Материал Материал { get; set; }
    }
}
