//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerServiceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставЗаказа_Материалы
    {
        public int idПозиция { get; set; }
        public Nullable<int> idЗаказ { get; set; }
        public Nullable<int> idМатериал { get; set; }
        public Nullable<decimal> Количество { get; set; }
        public Nullable<decimal> ЦенаЗаЕдиницу { get; set; }
        public Nullable<decimal> СтоимостьПозиции { get; set; }
        public Nullable<int> idСтатус { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Материал Материал { get; set; }
        public virtual Статус Статус { get; set; }
    }
}
