//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerServiceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Счет
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Счет()
        {
            this.Платеж = new HashSet<Платеж>();
        }
    
        public int idСчет { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<System.DateTime> ДатаСчета { get; set; }
        public Nullable<int> idЗаказ { get; set; }
        public Nullable<bool> СтатусОплаты { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Платеж> Платеж { get; set; }
    }
}
